apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "devopsdemo.fullname" . }}ingress
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "devopsdemo.fullname" . }}-service
          servicePort: 80
