apiVersion: v1
kind: Service
metadata:
  name: {{ template "devopsdemo.fullname" . }}-service
  namespace: default
spec:
  ports:
  - name: tcp-80-80
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: demo-devops
  type: NodePort
  sessionAffinity: None
