apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-devops-ingress
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: demo-devops-service
          servicePort: 80
